---
name: Rust

on:
  push:
    branches: [ "addCI" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build deps
      run: |
        sudo apt-get install -y libarchive-dev libcairo2-dev libpoppler-glib-dev
        cargo install grass just
        rustup toolchain install nightly
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - uses: actions/checkout@v4

    - name: Build
      run: just build

    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: eloran

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: eloran-linux-amd64
        path: ./target/x86_64-unknown-linux-gnu/release/eloran
