---
name: Rust

on:
  push:
    branches: [ "addCI" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install build deps
      run: sudo apt-get install -y libarchive-dev libcairo2-dev libpoppler-glib-dev
    - name: Install grass compiler and just
      run: cargo install grass just
    - uses: actions/checkout@v4
    - name: Build
      run: just build
    # - name: Build
    #   run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
